<?php
/**
 * See LICENSE.md for license details.
 */

/** @var \Magento\Backend\Block\Template $block */
?>
<div class="dhl-shipping-custom-info">
    <header>
        <?php /* @noEscape */ echo $block->getTest(); ?>
        <img src="<?php /* @noEscape */ echo $block->getLogo(); ?>">
        <p class="info">Version <?php /* @noEscape */ echo $block->getModuleVersion(); ?></p>
    </header>
    <div class="container">
        <div class="row">
            <?php /* @noEscape */ echo $block->getBlockHtml('adminhtml\system\config\form\field\custominformation_0.custom_information_copy'); ?>
        </div>
    </div>
</div>
