<?php
/**
 * See LICENSE.md for license details.
 */

/**
 * @var $block \Magento\Backend\Block\Template
 * @see \Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray::renderCellTemplate
 * @see \Dhl\ShippingCore\Block\Adminhtml\System\Config\Form\Field\Package::getTemplateRenderer
 */
$elId = $block->getInputId();
$elName = $block->getInputName();
$column = $block->getColumn();

$name = str_replace('[<%- _id %>]', '', $elName);
$size = $column['size'] ?: '';
$style = $column['style'] ?: '';
$class = $column['class'] ?? 'input-radio';
?>
<input type="radio" value="<%-_id %>" id="<?= $elId ?>" name="<?= $name ?>" size="<?= $size ?>" style="<?= $style ?>" class="<?= $class ?>"/>