<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dhl\ShippingCore\ViewModel\Adminhtml\System\InfoBox $viewModel */
$viewModel = $block->getData('view_model');
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('The new DHL Shipping extension covers all available DHL services for your Magento 2 store. It consolidates all DHL functionalities in one solution ready to activate with your DHL account credentials.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('You can configure all settings here that apply to all available DHL shipping methods, such as shipping options, checkout services and return solutions.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(
            __(
                'Further settings related to shipping can be specified in the %1Parcel Processing%3 and %2Batch Processing%3 config groups.',
                '<a href="' . $block->escapeUrl($viewModel->getParcelProcessingConfigUrl()) . '">',
                '<a href="' . $block->escapeUrl($viewModel->getBatchProcessingConfigUrl()) . '">',
                '</a>'
            ),
            ['a']
        ) ?>
    </p>
    <p>
        <button id="dhl-show-modal-button" class="button secondary" type="button"><?= __('Validate Configuration') ?></button>
    </p>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('Post & DHL and Magento')) ?></h3>
            <p>
                <?= $block->escapeHtml(__('Having issues configuring the extension? Contact our support desk: ')) ?>
                <a href="mailto:<?= $block->escapeHtml(__('dhl.support@netresearch.de')) ?>">
                    <?= $block->escapeHtml(__('dhl.support@netresearch.de')) ?>
                </a>
            </p>
        </div>
    </aside>
</div>
<div hidden>
    <iframe id="dhl-config-validation-modal" class="modal" height="100%" width="100%" style="border: none; min-height: 20vh"
            loading="eager"></iframe>
</div>
<script type="text/javascript">
    window.addEventListener("DOMContentLoaded", function () {
        require(["jquery", "Magento_Ui/js/modal/modal"], function ($) {
            $("#dhl-config-validation-modal").modal({
                title: "<?= $block->escapeHtml(__('Validation Result')) ?>",
                trigger: "#dhl-show-modal-button",
                clickableOverlay: true,
                responsive: true,
                buttons: [],
                modalClass: 'dhl-validation-popup',
                opened: function (event) {
                    this.src = "<?= $block->escapeUrl($viewModel->getConfigValidationUrl()) ?>";
                }
            });
        });
    });
</script>
