<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Netresearch\ShippingCore\ViewModel\Adminhtml\System\InfoBox $viewModel */
$viewModel = $block->getData('view_model');
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('The new DHL Shipping extension covers all available DHL services for your Magento 2 store. It consolidates all DHL functionalities in one solution ready to activate with your DHL account credentials.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('You can configure all settings here that apply to all available DHL shipping methods, such as shipping options, checkout services and return solutions.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(
            __(
                'Further settings related to shipping can be specified in the %1Parcel Processing%3 and %2Batch Processing%3 config groups.',
                '<a href="' . $block->escapeUrl($viewModel->getParcelProcessingConfigUrl()) . '">',
                '<a href="' . $block->escapeUrl($viewModel->getBatchProcessingConfigUrl()) . '">',
                '</a>'
            ),
            ['a']
        ) ?>
    </p>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('Post & DHL and Magento')) ?></h3>
            <p>
                <?= $block->escapeHtml(__('Having issues configuring the extension? Contact our support desk: ')) ?>
                <a href="mailto:<?= $block->escapeHtml(__('dhl.support@netresearch.de'))?>">
                    <?= $block->escapeHtml(__('dhl.support@netresearch.de'))?>
                </a>
            </p>
        </div>
    </aside>
</div>
