<?php
/**
 * See LICENSE.md for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Netresearch\ShippingCore\ViewModel\Adminhtml\System\InfoBox $viewModel */
$viewModel = $block->getData('view_model');
$moduleVersion = $viewModel->getModuleVersion();
?>
<?php if ($moduleVersion): ?>
    <p class="info">
        <a href="https://marketplace.magento.com/dhl-shipping-m2.html" target="_blank" rel="noreferrer">
            <?= $block->escapeHtml('Deutsche Post & DHL Shipping') ?>
        </a>
        <?= $block->escapeHtml($moduleVersion) ?>
    </p>
<?php endif; ?>
