<?php
/**
 * See LICENSE.md for license details.
 */
declare(strict_types=1);

/** @var $block Magento\Shipping\Block\Adminhtml\Order\Packaging */
?>
<div id="packaging-window" data-mage-init='{"Dhl_ShippingCore/js/packaging-controller": {}}'>
<!--  @TODO render component content here  -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Dhl_ShippingCore/js/packaging": {
                "target": "#packaging-window",
                "options": {
                    "title": "Packaging popup",
                    "type": "slide",
                    "buttons": []
                }
            }
        }
    }
</script>
